### ISSUE TITLE
Problem installing @vue/cli on Windows10

### ISSUE THREAD

**Issue by alfianpp** [volta-cli/volta#1010]
Hello, I have a problem installing `@vue/cli` with volta
I got a message like this after a successful install and want to run it,

```
'C:\Users\Alfian' is not recognized as an internal or external command, operable program or batch file.
```

```
volta install @vue/cli
success: installed @vue/cli@4.5.13 with executables: vue

volta which vue
C:\Users\Alfian Putra Persada\AppData\Local\Volta\tools\image\packages\@vue/cli\vue
```

This doesn't happen when installing anything else, for example `firebase-tools`

Thank you,

**Comment by charlespierce** [comment]
Hi @alfianpp, that's a tricky one. Base on the error, it looks like it might be related to the username having spaces in it (since it seems to think that only the part before the space is the command). However, what's confusing is that it's not happening for other tools. Volta handles all 3rd party tools effectively the same, so there shouldn't be any difference in behavior between e.g. `@vue/cli` and `firebase-tools`. If we were handling the path incorrectly, it would fail for all of those tools, since they're all installed in sibling directories.

The fact that it's failing makes me wonder if there's something internal in `@vue/cli` that is trying to execute a program and mishandling the spaces, which only shows up because Volta happens to use your home directory instead of a global directory without spaces.

Out of curiosity, could you try running the Vue CLI directly? Either by navigating to the directory that comes out of `volta which vue` or by running the JS file directly (I'm estimating what the path would be, but you need to find the `@vue/cli/bin/vue.js` file underneath the Volta image directory)?

```
node "C:\Users\Alfian Putra Persada\AppData\Local\Volta\tools\image\packages\@vue/cli\node_modules\@vue\cli\bin\vue.js"
```

That should help us understand if it's Volta mishandling the execution or something within Vue itself.

**Comment by alfianpp** [comment]
Hi @charlespierce, thanks for replying, I tried running the command you said and got this

```
node ""C:\Users\Alfian Putra Persada\AppData\Local\Volta\tools\image\packages\@vue\cli\node_modules\@vue\cli\bin\vue.js""

internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'C:\Users\Alfian'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:864:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)[39m
[90m    at internal/main/run_main_module.js:18:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}
```

**Comment by charlespierce** [comment]
Hi @alfianpp, sorry for the delay! Looking at that output, I think the issue is actually the combination of the spaces in the username and the name of the package including a scope: The spaces seem to turn the path into an exact path, so appending `@vue/cli` into it causes Volta to treat it as a folder name ("@vue/cli") instead of two nested folders ("@vue" and "cli").

Out of curiosity, if you navigate to the parent directory (`C:\Users\Alfian Putra Persada\AppData\Local\Volta\tools\image\packages\`) what folders do you see? Do you see `@vue` or `@vue/cli`? I'm guessing you'll see the former which means what Volta is doing to call the binary is incorrect. If I get a chance, I'll see if I can reproduce this locally.

**Comment by hedgehog1029** [comment]
I'm also running into this issue, here's the rundown:

```
λ volta which vue
C:\Users\Henry Le Grys\AppData\Local\Volta\tools\image\packages\@vue/cli\vue
```

![Actual path](https://a.pomf.cat/pwdcwu.PNG)

so it looks like volta is constructing the command line badly. windows does support forward slashes in paths but it seems like mixing them is mucking something internal up? debug logs might help out here to see exactly where volta is failing...

you should be able to replicate this problem state with `volta install @vue/cli`

**Comment by hedgehog1029** [comment]
okay well i did some investigating and it is not the mixed slashes. it is, in fact, a documented behaviour of cmd.exe:

```
If /C or /K is specified, then the remainder of the command line after
the switch is processed as a command line, where the following logic is
used to process quote (") characters:

    1.  If all of the following conditions are met, then quote characters
        on the command line are preserved:

        - no /S switch
        - exactly two quote characters
        - no special characters between the two quote characters,
          where special is one of: &<>()@^|
        - there are one or more whitespace characters between the
          two quote characters
        - the string between the two quote characters is the name
          of an executable file.

    2.  Otherwise, old behavior is to see if the first character is
        a quote character and if so, strip the leading character and
        remove the last quote character on the command line, preserving
        any text after the last quote character.
```

rust automatically surrounds arguments with quote characters on windows. since the folder name has an `@`, the quotes are stripped out of the command line, which then means that the command line is no longer treated as a single path to an executable and instead it trips up at the first space character.

i guess the solution to this is removing the `@`? presumably we need another way to differentiate scopes with subfolders from just regular unscoped packages...

**Comment by AaronBeaudoin** [comment]
Still running into this issue. First I run:

```
npm install -g @angular/cli
```

Afterwards I run `ng` and get:

```
'C:\Users\Aaron' is not recognized as an internal or external command, operable program or batch file.
```

If I run `where.exe ng` I get:

```
C:\Users\Aaron Beaudoin\AppData\Local\Volta\bin\ng
C:\Users\Aaron Beaudoin\AppData\Local\Volta\bin\ng.exe
```

If I run `C:\Users\"Aaron Beaudoin"\AppData\Local\Volta\tools\image\packages\@angular\cli\ng.cmd --help`:

```
ng <command>

Commands:
  ng add <collection>            Adds support for an external library to your project.
  ng analytics                   Configures the gathering of Angular CLI usage metrics.
  ng build [project]             Compiles an Angular application or library into an output directory named dist/ at the given output path.                                                                                                                                                [aliases: b]
  ng cache                       Configure persistent disk cache and retrieve cache statistics.
  ng completion                  Set up Angular CLI autocompletion for your terminal.
  ng config [json-path] [value]  Retrieves or sets Angular configuration values in the angular.json file for the workspace.
  ng deploy [project]            Invokes the deploy builder for a specified project or for the default project in the workspace.
  ng doc <keyword>               Opens the official Angular documentation (angular.io) in a browser, and searches for a given keyword.                                                                                                                                                    [aliases: d]
  ng e2e [project]               Builds and serves an Angular application, then runs end-to-end tests.                                                                                                                                                                                    [aliases: e]
  ng extract-i18n [project]      Extracts i18n messages from source code.
  ng generate                    Generates and/or modifies files based on a schematic.                                                                                                                                                                                                    [aliases: g]
  ng lint [project]              Runs linting tools on Angular application code in a given project folder.
  ng new [name]                  Creates a new Angular workspace.                                                                                                                                                                                                                         [aliases: n]
  ng run <target>                Runs an Architect target with an optional custom builder configuration defined in your project.
  ng serve [project]             Builds and serves your application, rebuilding on file changes.                                                                                                                                                                                          [aliases: s]
  ng test [project]              Runs unit tests in a project.                                                                                                                                                                                                                            [aliases: t]
  ng update [packages..]         Updates your workspace and its dependencies. See https://update.angular.io/.
  ng version                     Outputs Angular CLI version.                                                                                                                                                                                                                             [aliases: v]

Options:
  --help  Shows a help message for this command in the console.                                                                                                                                                                                                                              [boolean]

For more information, see https://angular.io/cli/.
```

So the command itself works just fine. But when running through Volta it doesn't work.

**Comment by charlespierce** [comment]
Hi @AaronBeaudoin, thanks for the extra info, I think I have an idea what's going on! Are you by chance using Git Bash (or a similar Bash emulator) to execute `ng`? We install a shim for Git Bash specifically (named the same as the command but without the `.exe` extension) since it has some unintuitive behavior (see [this comment](https://github.com/volta-cli/volta/blob/7f217494842e3d28d67133b8ba387a1598314fd7/crates/volta-core/src/shim.rs#L117-L124) for more details).

That shim calls `cmd.exe` using `$0` as the first argument, which is the path to the current executable. However, it mistakenly isn't quoting that argument, so when there is a space in the path, it's not interpreted correctly. As a quick check, if you edit the `C:\Users\{username}\AppData\Local\Volta\bin\ng` script to the following, does it work?

```
cmd //C "$0" "$@"
```
(Which should be only adding quotes around `$0`)

**Comment by AkshayKumar-1729** [comment]
Hi,

I am writing to confirm that this issue still persists as of July 2, 2025, on my Windows system with a username containing spaces. I've performed extensive diagnostics that might help further pinpoint the problem.

**Problem Description:**
When my Windows username contains a space (e.g., `K Akshay Kumar`), executing global npm packages installed via Volta (like `@google/gemini-cli`) fails in `cmd.exe` with an error indicating path truncation: `'C:\Users\K' is not recognized as an internal or external command, operable program or batch file.`. This occurs despite `volta.exe` itself working, and `volta run node` also working correctly. The issue appears to be Volta's internal path resolution for global npm package executables.

**To Reproduce (Detailed Diagnostics):**
1.  **System Setup:**
    * Windows 10.0.26100.4349 (as per my logs) with a username containing a space (`K Akshay Kumar`).
    * Volta CLI installed (`volta.exe` located at `C:\Program Files\Volta\volta.exe`).
    * Initially, default `VOLTA_HOME` (i.e., `C:\Users\K Akshay Kumar\AppData\Local\Volta`).

2.  **Steps:**
    a. Open `cmd.exe`.
    b. Confirmed `volta.exe` location:
       ```
       C:\Users\K Akshay Kumar>where volta
       C:\Program Files\Volta\volta.exe
       ```
    c. Confirmed `volta` basic functionality:
       ```
       C:\Users\K Akshay Kumar>"C:\Program Files\Volta\volta.exe" --version
       2.0.2
       ```
    d. Confirmed `volta run node` functionality (which also involves user-specific paths):
       ```
       C:\Users\K Akshay Kumar>"C:\Program Files\Volta\volta.exe" run node --version
       v22.16.0
       ```
    e. Installed a global npm package using Volta (`@google/gemini-cli`):
       ```
       C:\Users\K Akshay Kumar>volta install @google/gemini-cli
       success: installed @google/gemini-cli@0.1.9 with executables: gemini
       ```
    f. Attempted to execute the global package:
       ```
       C:\Users\K Akshay Kumar>gemini
       'C:\Users\K' is not recognized as an internal or external command,
       operable program or batch file.
       ```
    g. Confirmed `gemini` executable location (before the workaround):
       ```
       C:\Users\K Akshay Kumar>where gemini
       C:\Users\K Akshay Kumar\AppData\Local\Volta\bin\gemini
       C:\Users\K Akshay Kumar\AppData\Local\Volta\bin\gemini.cmd
       ```
    h. Manually executed the `gemini.cmd` shim with quotes (as Volta initially generated it):
       ```
       C:\Users\K Akshay Kumar>"C:\Users\K Akshay Kumar\AppData\Local\Volta\bin\gemini.cmd"
       'C:\Users\K' is not recognized as an internal or external command,
       operable program or batch file.
       ```
    i. Examined `gemini.cmd` content (standard Volta shim):
       ```batch
       @echo off
       volta run %~n0 %*
       ```
    j. Manually executed the command the shim tries to run (the most crucial test):
       ```
       C:\Users\K Akshay Kumar>"C:\Program Files\Volta\volta.exe" run gemini
       'C:\Users\K' is not recognized as an internal or external command,
       operable program or batch file.
       ```
    k. (Note: `gemini` also failed when attempting to run in PowerShell, indicating it's not strictly a `cmd.exe`-only parsing issue at the very end).

**Expected behavior:**
The `gemini` command should execute successfully, displaying the Gemini CLI help or version information, just like `volta run node --version` does.

**Workaround (Successful):**
Setting the `VOLTA_HOME` environment variable to a path without spaces and then reinstalling Node.js and global packages successfully resolves the issue.

Steps for successful workaround:
1.  Set User Environment Variable `VOLTA_HOME` to `C:\VoltaHome` (or similar path without spaces).
2.  Update User `PATH` variable to remove the old `%USERPROFILE%\AppData\Local\Volta\bin` and add `C:\VoltaHome\bin`.
3.  Restart computer.
4.  `volta install node@22.16.0`
5.  `volta install @google/gemini-cli`
6.  `gemini` now works correctly.

**Environment:**
* **OS:** Windows 11 Home Single Language, Version 24H2, OS build 26100.4349
* **Volta Version:** 2.0.2
* **Node.js Version (managed by Volta):** v22.16.0
* **NPM Version (managed by Volta):** 10.9.2
* **User Name:** Contains spaces (`K Akshay Kumar`)
* **Shell:** `cmd.exe` (issue also confirmed in PowerShell before workaround)

**Additional context:**
This issue seems to arise from `volta.exe`'s internal path resolution for global npm package executables. Despite `volta.exe` being able to launch Node.js correctly (which is also within the user's spaced path), it specifically fails when launching global npm packages where the path to the package's entry point contains the user's spaced username. The error suggests an internal path construction or passing mechanism within `volta.exe` is not quoting the path correctly.

Hope this detailed report helps in resolving this issue!
