### ISSUE TITLE
Windows spawn node process with IPC failed

### ISSUE THREAD

**Issue by WeslyG** [volta-cli/volta#1032]
Hi, I want to say thank you for developing volta, this is a very cool tool!

I ran into a strange problem, after installing vista on windows 10, my tests written in Mocha stopped being displayed in vscode.

I use this plugin to run my tests  https://github.com/hbenl/vscode-mocha-test-adapter

In the console, I saw the message
```
2021-09-27 10:41:38.355] [DEBUG] Using nodePath: C:\Program Files\Volta\node.exe
[2021-09-27 10:41:38.497] [ERROR] Worker (stderr): child_process.js:159
  p.open(fd);
    ^

Error: EBADF: bad file descriptor, uv_pipe_open
    at Object._forkChild (child_process.js:159:5)
    at setupChildProcessIpcChannel (internal/bootstrap/pre_execution.js:356:30)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:53:3)
    at internal/main/run_main_module.js:7:1 {
  errno: -4083,
  code: 'EBADF',
  syscall: 'uv_pipe_open'
}

[2021-09-27 10:41:38.505] [ERROR] Couldn't load options using mocha: child process exited with code 1 and signal null
```

I looked at the code of the vscode extension that runs the tests, and found the following there

```
const stdio = ["pipe", "pipe", "pipe", "ipc"];
        let childProc;
        if (nodePath) {
          childProc = child_process_1.spawn(
            nodePath,
            [...nodeArgv, childProcScript, ...argv],
            { cwd, stdio }
          );
        }
```

After searching the network for similar problems, I realized that this is due to the behavior of the spawn process nodejs + IPC (there is no error without ipc).

I specified the direct path to the bin of the real nodejs in the configuration file like this
```
"mochaExplorer.nodePath": "C:\\Users\\%USERNAME%\\AppData\\Local\\Volta\\tools\\image\\node\\12.22.3\\node.exe"
```
And it works.

However, I want to understand why volta does not proxy the ipc channel, or there may be an error somewhere deeper. 
Anyway, I'll be glad if you take a look at this.

**Comment by WeslyG** [comment]
In the source code, this line is here
https://github.com/hbenl/vscode-mocha-test-adapter/blob/master/src/optsReader.ts#L128

**Comment by charlespierce** [comment]
Hi @WeslyG, thanks for reporting! I believe the core issue is in how the Volta shims work. According to the [`child_process` docs](https://nodejs.org/api/child_process.html#child_process_options_stdio) (emphasis added):

> Accessing the IPC channel fd in any way other than process.send() or **using the IPC channel with a child process that is not a Node.js instance is not supported**.

Volta's shims are native binaries, _not_ Node processes (though they launch Node processes), so the connection is broken there. I don't know of a clean way to forward something like the IPC channel, because it's entirely an internal implementation detail of Node spawning another Node process.
