### ISSUE TITLE
pm2 startup failed with "thread 'main' panicked at 'failed to spawn thread: Os"

### ISSUE THREAD

**Issue by halofe** [volta-cli/volta#1570]
```bash
➜  demo-app git:(main) ✗ pm2 startup
[PM2] Init System found: systemd
[PM2] To setup the Startup Script, copy/paste the following command:
sudo env PATH=$PATH:/home/ubuntu/.volta/tools/image/node/21.1.0/bin /home/ubuntu/.volta/tools/image/packages/pm2/lib/node_modules/pm2/bin/pm2 startup systemd -u ubuntu --hp /home/ubuntu
➜  demo-app git:(main) ✗ sudo env PATH=$PATH:/home/ubuntu/.volta/tools/image/node/21.1.0/bin /home/ubuntu/.volta/tools/image/packages/pm2/lib/node_modules/pm2/bin/pm2 startup systemd -u ubuntu --hp /home/ubuntu
thread 'main' panicked at 'failed to spawn thread: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ctrlc-3.2.4/src/lib.rs:117:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
➜  demo-app git:(main) ✗ sudo env PATH=$PATH pm2 startup systemd -u ubuntu --hp /home/ubuntu
thread 'main' panicked at 'failed to spawn thread: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ctrlc-3.2.4/src/lib.rs:117:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
➜  demo-app git:(main) ✗ node -v
v21.1.0
➜  demo-app git:(main) ✗ pm2 -v
5.3.0
➜  demo-app git:(main) ✗ which node
/home/ubuntu/.volta/bin/node
➜  demo-app git:(main) ✗ which pm2
/home/ubuntu/.volta/bin/pm2
```

**Comment by shangxinbo** [comment]
same error

**Comment by chriskrycho** [comment]
How odd! Can you share the results of running with `RUST_BACKTRACE=1`, as the error output indicates? That will help us see why it's going wrong that way.

**Comment by shangxinbo** [comment]
我试过了，使用volta或者类似的node管理工具时，node和PM2安装是只给一个用户安装，所以在执行sudo命令时会有问题，可以尝试给root安装pm2解决。
因为这个问题我决定以后再也不用nvm，volta这种东西了

**Comment by halofe** [comment]
The command succeed after `sudo -i`
```
➜  ~ pm2 startup
[PM2] Init System found: systemd
[PM2] To setup the Startup Script, copy/paste the following command:
sudo env PATH=$PATH:/home/ubuntu/.volta/tools/image/node/21.1.0/bin /home/ubuntu/.volta/tools/image/packages/pm2/lib/node_modules/pm2/bin/pm2 startup systemd -u ubuntu --hp /home/ubuntu
➜  ~ sudo -i
root@e1:~# env PATH=$PATH:/home/ubuntu/.volta/tools/image/node/21.1.0/bin /home/ubuntu/.volta/tools/image/packages/pm2/lib/node_modules/pm2/bin/pm2 startup systemd -u ubuntu --hp /home/ubuntu
[PM2] Init System found: systemd
```

**Comment by halofe** [comment]
> How odd! Can you share the results of running with `RUST_BACKTRACE=1`, as the error output indicates? That will help us see why it's going wrong that way.

Tried with RUST_BACKTRACE=1, error with "pm2 not found"
