### ISSUE TITLE
Internal Error: EPERM: operation not permitted, open '...\.yarn\cache\.gitignore'

### ISSUE THREAD

**Issue by Marvin-Brouwer** [volta-cli/volta#1656]
Hi,

I've been using volta for `pnpm` and `npm` for a while now.
I just tried to install `yarn` and it's just not working.

I get the following error:

```text
Internal Error: EPERM: operation not permitted, open 'D:\...\.yarn\cache\.gitignore'
```

I tried multiple yarn versions, git bash, windows cmd, with and without admin rights.

**Comment by Marvin-Brouwer** [comment]
My `pnpm` also broke. So I rebooted.
Now I get this on yarn4:
https://github.com/volta-cli/volta/issues/1054
```txt
Error: @sveltejs/package@patch:@sveltejs/package@npm:1.0.0-next.1#.yarn/patches/@sveltejs-package-npm-1.0.0-next.1-2fd015530b.patch::locator=%40builder.io%2Fmitosis-repo%40workspace%3A.: ENOENT: no such file or directory, open 'D:\...\.yarn\patches\@sveltejs-package-npm-1.0.0-next.1-2fd015530b.patch'
```
And this on yarn3:
```text
Internal Error: @builder.io/mitosis-repo@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at tF.getCandidates (C:\Users\...\AppData\Local\Volta\tools\image\yarn\3.2.0\bin\yarn.js:437:4480)
    at wd.getCandidates (C:\Users\...\AppData\Local\Volta\tools\image\yarn\3.2.0\bin\yarn.js:395:1281)
    at C:\Users\...\AppData\Local\Volta\tools\image\yarn\3.2.0\bin\yarn.js:441:7765
    at Pg (C:\Users\...\AppData\Local\Volta\tools\image\yarn\3.2.0\bin\yarn.js:394:11098)
    at le (C:\Users\...\AppData\Local\Volta\tools\image\yarn\3.2.0\bin\yarn.js:441:7745)
    at async Promise.allSettled (index 0)
    at async co (C:\Users\...\AppData\Local\Volta\tools\image\yarn\3.2.0\bin\yarn.js:394:10390)
    at async C:\Users\...\AppData\Local\Volta\tools\image\yarn\3.2.0\bin\yarn.js:441:8295
    at async pi.startProgressPromise (C:\Users\...\AppData\Local\Volta\tools\image\yarn\3.2.0\bin\yarn.js:394:47994)
    at async ze.resolveEverything (C:\Users\...\AppData\Local\Volta\tools\image\yarn\3.2.0\bin\yarn.js:441:6285)
```

**Comment by Marvin-Brouwer** [comment]
I have some more information.
My (company managed) virus scanner seems to block the node.exe because it's in an odd place.
After that happens all yarn process end up failing with `EPERM` until I reboot.
I'm currently in contact with some people to get this resolved and I'll try again if/when the block is lifted.

**Comment by Marvin-Brouwer** [comment]
UPDATE: It was indeed the virus scanner
