### ISSUE TITLE
TypeError: Cannot create property 'lastUpdateCheck' on string 'lastUpdateCheck 1723621905528 nodeLinker node-modules ces'

### ISSUE THREAD

**Issue by MuttakinHasib** [volta-cli/volta#1841]
throwing this error on my NX React Native project after running `yarn install` command:

![CleanShot 2024-08-14 at 2  47 26@2x](https://github.com/user-attachments/assets/fe3f5948-bbc1-4821-88bb-93939137ad95)

**Comment by MuttakinHasib** [comment]
@chriskrycho please take a look

**Comment by chriskrycho** [comment]
Thanks for filing the issue. A couple of notes:

1. Please use `which yarn` and `volta which yarn` to confirm that you’re actually running the Volta-managed version.
2. Please confirm that this happens with the same Yarn and Node versions when *not* using Volta!
3. Please follow the instructions from our [Docs > Contributing > Debugging](https://docs.volta.sh/contributing/#debugging) guide, and for any Volta commands you execute directly, run with `--verbose`. Then share the relevant output here!
4. Please copy and paste the text from your terminal, rather than posting screenshots! That's generally helpful even for me, but it's especially helpful for anyone blind or otherwise with worse vision.

That should help us debug if it is actually a Volta issue. Thanks!

**Comment by MuttakinHasib** [comment]
1. **Yarn Path Verification:**
   - Output of `which yarn`: `/Users/hasib/.volta/bin/yarn`
   - Output of `volta which yarn`: `/Users/hasib/.volta/tools/image/yarn/1.22.22/bin/yarn`

2. **Version Testing:**
   - I'm using Yarn v1.22.22 installed via Volta. I tested with `bun install` and did not encounter the issue.

3. **Verbose Output:**
   - Here’s the output when running `y --verbose`:
   ```
   [verbose] Found default configuration at '/Users/hasib/.volta/tools/user/platform.json'
   [verbose] node@20.12.2 has already been fetched, skipping download
   [verbose] yarn@1.22.22 has already been fetched, skipping download
   [verbose] Active Image:
       Node: 20.12.2 from default configuration
       npm: 10.5.0 from default configuration
       pnpm: None
       Yarn: 1.22.22 from default configuration
   yarn install v1.22.22
   verbose 0.109418833 Checking for configuration file "/Users/hasib/Development/Projects/igot-sdk/.npmrc".
   verbose 0.109565333 Checking for configuration file "/Users/hasib/.npmrc".
   verbose 0.109769333 Found configuration file "/Users/hasib/.npmrc".
   verbose 0.110327292 Checking for configuration file "/Users/hasib/.volta/tools/image/node/20.12.2/etc/npmrc".
   verbose 0.1103955 Checking for configuration file "/Users/hasib/Development/Projects/igot-sdk/.npmrc".
   verbose 0.110564208 Checking for configuration file "/Users/hasib/Development/Projects/.npmrc".
   verbose 0.110738167 Checking for configuration file "/Users/hasib/Development/.npmrc".
   verbose 0.11087625 Checking for configuration file "/Users/hasib/.npmrc".
   verbose 0.110932375 Found configuration file "/Users/hasib/.npmrc".
   verbose 0.111069542 Checking for configuration file "/Users/.npmrc".
   verbose 0.112135 Checking for configuration file "/Users/hasib/Development/Projects/igot-sdk/.yarnrc".
   verbose 0.112277667 Checking for configuration file "/Users/hasib/.yarnrc".
   verbose 0.112337917 Found configuration file "/Users/hasib/.yarnrc".
   verbose 0.112440667 Checking for configuration file "/Users/hasib/.volta/tools/image/node/20.12.2/etc/yarnrc".
   verbose 0.112498542 Checking for configuration file "/Users/hasib/Development/Projects/igot-sdk/.yarnrc".
   verbose 0.112608708 Checking for configuration file "/Users/hasib/Development/Projects/.yarnrc".
   verbose 0.112675 Checking for configuration file "/Users/hasib/Development/.yarnrc".
   verbose 0.112730792 Checking for configuration file "/Users/hasib/.yarnrc".
   verbose 0.112773875 Found configuration file "/Users/hasib/.yarnrc".
   verbose 0.112956458 Checking for configuration file "/Users/.yarnrc".
   verbose 0.115678 current time: 2024-08-14T13:40:05.153Z
   verbose 0.150998625 Performing "GET" request to "https://yarnpkg.com/latest-version".
   [1/4] 🔍  Resolving packages...
   success Already up-to-date.
   ✨  Done in 0.29s.
   verbose 0.808690167 Request "https://yarnpkg.com/latest-version" finished with status code 200.
   TypeError: Cannot create property 'lastUpdateCheck' on string 'lastUpdateCheck 1723621905528 nodeLinker node-modules ces'
       at YarnRegistry.<anonymous> (/Users/hasib/.volta/tools/image/yarn/1.22.22/lib/cli.js:92927:30)
       at Generator.next (<anonymous>)
       at step (/Users/hasib/.volta/tools/image/yarn/1.22.22/lib/cli.js:310:30)
       at /Users/hasib/.volta/tools/image/yarn/1.22.22/lib/cli.js:328:14
       at new Promise (<anonymous>)
       at new F (/Users/hasib/.volta/tools/image/yarn/1.22.22/lib/cli.js:5539:28)
       at YarnRegistry.<anonymous> (/Users/hasib/.volta/tools/image/yarn/1.22.22/lib/cli.js:307:12)
       at YarnRegistry.saveHomeConfig (/Users/hasib/.volta/tools/image/yarn/1.22.22/lib/cli.js:92934:20)
       at Install.<anonymous> (/Users/hasib/.volta/tools/image/yarn/1.22.22/lib/cli.js:7933:35)
       at Generator.next (<anonymous>)
   [verbose] No custom hooks found
   ```
Thanks @chriskrycho

**Comment by charlespierce** [comment]
@MuttakinHasib Can you verify if this happens in Yarn 1.22.22 without Volta? From the error message, it looks like it's happening within Yarn itself, so `bun install` isn't a good comparison as it doesn't use Yarn.

**Comment by MuttakinHasib** [comment]
Thanks for your help. I don't know what the issue was but I completely removed Yarn and reinstalled it with volta, and now it's working.
