### ISSUE TITLE
Volta install `neovim` package is not compatible with Neovim.

### ISSUE THREAD

**Issue by scull7** [volta-cli/volta#606]
I attempted to use Volta to install the Node.JS support package for Neovim.  However, because the shim is directly executable and not interpretable by `node`, the plugin fails to execute.

```sh
## Node.js provider (optional)
  - INFO: Node.js: v12.13.0
  - INFO: Neovim node.js host: /usr/local/bin/neovim-node-host
  - ERROR: Command error (job=12, exit code 1): `node /usr/local/bin/neovim-node-host --version` (in '/Users/nathansculli')
    Output: /Users/nathansculli/.volta/shim:1����^GSyntaxError: Invalid or unexpected token    at Module._compile (internal/modules/cjs/loader.js:892:18)    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)    at Module.load (internal/modules/cjs/    loader.js:812:32)    at Function.Module._load (internal/modules/cjs/loader.js:724:14)    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)    at internal/main/run_main_module.js:17:11
    Stderr: /Users/nathansculli/.volta/shim:1����^GSyntaxError: Invalid or unexpected token    at Module._compile (internal/modules/cjs/loader.js:892:18)    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)    at Module.load (internal/modules/cjs/    loader.js:812:32)    at Function.Module._load (internal/modules/cjs/loader.js:724:14)    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)    at internal/main/run_main_module.js:17:11
  - ERROR: Failed to run: ['node', '/usr/local/bin/neovim-node-host', '--version']
    - ADVICE:
      - Report this issue with the output of: 
      - ['node', '/usr/local/bin/neovim-node-host', '--version']
```

Neovim is attempting to run the `neovim-node-host` script with `node`.  When I attempt to do the same I receive the below error:
```sh
node /usr/local/bin/neovim-node-host --version
/Users/nathansculli/.volta/shim:1
����


SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by charlespierce** [comment]
Hi @scull7, this is another odd one. What command are you running, and in what context, that caused the first error? Volta doesn't install anything in `/usr/local/bin`, so that file must be provided by some other package (and is likely binary, which explains why executing it with `node` doesn't work).

However, if you do `volta install neovim`, it should install the package within the `.volta` folder, and that package _does_ provide a javascript file that should be executed (namely `bin/cli.js`, which it aliases to `neovim-node-host`). It looks like you might have a binary file with the same name earlier on your PATH, which is causing a conflict.

**Comment by scull7** [comment]
I used `volta install neovim`, it linked the `neovim-node-host` alias in `/usr/bin/local` to the `shim` in the `.volta` directory.  I made sure there was no other file using the path with `fd neovim-node-host /`

Sorry for bringing the weirdness today.

**Comment by charlespierce** [comment]
@scull7 No worries! Weirdness is good, it helps us find the corner cases that don't work! That's interesting about the `neovim` package, it must be doing something itself outside of what packages normally do. Is `/usr/local/bin/neovim-node-host` itself actually a symlink, or is it a small script that calls `node xxx`? If it's a symlink, what specifically does it link to? And if it's a script, can you show the contents?

Thanks for taking the time to help debug these issues!

**Comment by scull7** [comment]
it's a symlink which links to the the volta shim.  I'm happy to help, I like volta and want to be able to have it be the tool used for my team.

**Comment by charlespierce** [comment]
Okay, that explains why `node /usr/local/bin/neovim-node-host --version` doesn't work, as the Volta shim itself is a binary executable. However, running `neovim-node-host --version` directly _should_ work, if it's linked to the shim, because the shim should call the actual JS file that is provided by the package.

Is something internal to `neovim` attempting to run the `node /usr/local/bin/neovim-node-host` command? What's also strange is trying to figure out how that symlink was created in the first place.

**Comment by scull7** [comment]
Yes, neovim attempts to execute `node /usr/local/bin/neovim-node-host --version`, thus it fails because of the shim being a binary.

**Comment by scull7** [comment]
> What's also strange is trying to figure out how that symlink was created in the first place.

Yes, this is the weird part to me also.

**Comment by charlespierce** [comment]
Hi @scull7! It's been a little bit, but I was able to dig in somewhat here and find at least part of what is happening. Neovim itself does some detection to find the `neovim-node-host` script, and then calls `node <path_to_host> --version` as part of its setup ([see here](https://github.com/neovim/neovim/blob/31536ae003c0bd0ee311fc97b26ded0db8b3fa34/runtime/autoload/health/provider.vim#L607))

By default, that detection uses `npm` or `yarn` to do some work, which is how it's finding the symlink. However, the [documentation](https://github.com/neovim/neovim/blob/391706450445fc040d3b3766ace7d91ec13b1936/runtime/doc/provider.txt#L152) and the [detect method](https://github.com/neovim/neovim/blob/96be8a2c4d63faadb97c346abb336511a60ac89a/runtime/autoload/provider/node.vim#L50) show that this default resolution can be overridden with a variable: `g:node_host_prog`, which needs to point at the actual script file (since it will still ultimately be called with `node`).

Volta has a command that does the shim resolution: `volta which`, so I believe this can be made to work by adding the following to your `~/.vimrc` file:

```
let g:node_host_prog = system('volta which neovim-node-host')
```

Given that the behavior of calling `node <path>` is baked into `neovim`, I'm not sure if there's a better solution, but let me know if that works for you.

**Comment by thisguychris** [comment]
Hi, @charlespierce, not the OP but, I just want to add if I set the node_host_prog, I'm getting:

```vim
## Node.js provider (optional)
  - INFO: Node.js: v14.9.0
  - INFO: Nvim node.js host: /home/redacted/.volta/tools/image/packages/neovim/4.9.0/bin/cli.js

  - ERROR: Command error (job=9, exit code 1): `node '/home/redacted/.volta/tools/image/packages/neovim/4.9.0/bin/cli.js
    ' --version` (in '/home/redacted/opensource/foo')
    stderr: internal/modules/cjs/loader.js:895  throw err;  ^Error: Cannot find module '/home/redacted/.volta/tools/image/packages/neovim/4.9.0/bin/cli.js'    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)    at Function.Module._load (internal/modules/cjs/loader.js:742:27)    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)    at internal/main/run_main_module.js:17:47 {  code: 'MODULE_NOT_FOUND',  requireStack: []}
  - ERROR: Failed to run: ['node', '/home/redacted/.volta/tools/image/packages/neovim/4.9.0/bin/cli.js
    ', '--version']
    - ADVICE:
      - Report this issue with the output of: 
      - ['node', '/home/redacted/.volta/tools/image/packages/neovim/4.9.0/bin/cli.js
          ', '--version']
```

I'm able to get it work if I just use the path (without the bin/cli.js)
`let g:node_host_prog = '/home/redacted/.volta/tools/image/packages/neovim/4.9.0/'`

**Comment by jeffhertzler** [comment]
@thisguychris try `let g:node_host_prog = system('volta which neovim-node-host | tr -d "\n"')`. The volta which command is inserting a new line.

**Comment by thisguychris** [comment]
hey @jeffhertzler, that surprisingly worked thanks. 👌
Sadly, still getting error in #813
