### ISSUE TITLE
Volta error: Could not determine path to executable

### ISSUE THREAD

**Issue by alexdiliberto** [volta-cli/volta#615]
Using Volta to add the NPM package `empty-trash-cli`, this is my console output

```bash
alexdiliberto@AlexBookPro: ~/.volta/bin
$ volta install empty-trash-cli
Package empty-trash-cli@1.0.1 is already installed

alexdiliberto@AlexBookPro: ~/.volta/bin
$ which -a empty-trash 
/Users/alexdiliberto/.volta/bin/empty-trash

alexdiliberto@AlexBookPro: ~/.volta/bin
$ VOLTA_LOGLEVEL=debug RUST_BACKTRACE=full empty-trash 
Volta error: Could not determine path to executable 'empty-trash'

Please rerun the command that triggered this error with the environment
variables `VOLTA_LOGLEVEL` set to `debug` and `RUST_BACKTRACE` set to `full`, and open
an issue at https://github.com/volta-cli/volta/issues with the details!
[verbose] Error cause: No such file or directory (os error 2)

stack backtrace:
   0: backtrace::backtrace::trace::haa64515333367434 (0x1022ac55c)
   1: backtrace::capture::Backtrace::new_unresolved::hed822f3deb5bab22 (0x1022ab848)
   2: failure::backtrace::internal::InternalBacktrace::new::he4e485359fae4acb (0x1022aaf85)
   3: <failure::backtrace::Backtrace as core::default::Default>::default::h047799f9c4ee0416 (0x1022ab185)
   4: <E as volta_fail::FailExt>::with_context::h5ddf5cb489fd6bf0 (0x101f6ea2d)
   5: volta_core::tool::package::bin_full_path::hc23047158f24eb23 (0x101f4be4b)
   6: volta_core::run::binary::DefaultBinary::from_config::h2f62779c68c56def (0x101f51b68)
   7: volta_core::run::binary::DefaultBinary::from_name::h5f4673d41c3767e8 (0x101f522bf)
   8: volta_core::run::execute_tool::h0d31734251e3d5e5 (0x101f52f5b)
   9: shim::execute::run_shim::h8d9fb7c8ec58508f (0x101f03ef3)
  10: std::rt::lang_start::{{closure}}::h1b9027d55f6f07ad (0x101f02e86)
  11: std::panicking::try::do_call::ha1a4587e2a4eb439 (0x1022c8428)
  12: ___rust_maybe_catch_panic (0x1022d0e0f)
  13: std::rt::lang_start_internal::hcf96e32a124891dc (0x1022c8ece)
  14: _main (0x101f02b39)
Error details written to /Users/alexdiliberto/.volta/log/volta-error-2019-11-29_14_38_46.478.log
[verbose] No custom hooks found

```

**Comment by s0kil** [comment]
I'm having a similar issue, installing `pnpm`, It is located in `.volta/bin` but not available in `PATH`

**Comment by charlespierce** [comment]
Hi @alexdiliberto, thanks for reporting this! Can you share a few things to help debug what's going on here?

1. The contents of `~/.volta/tools/user/bins/empty-trash.json`
2. The output of `ls ~/.volta/tools/image/packages/empty-trash/1.0.1/`
3. The output of `volta which empty-trash` (I suspect this one will fail with the same error as was originally reported, but just to be sure)

Thanks!

@s0kil Can you go into more detail about what you mean by `pnpm` is located in `.volta/bin` but not available in `PATH`? Is `~/.volta/bin` not in your `PATH` at all, or is it just the one command that isn't working?

**Comment by s0kil** [comment]
@charlespierce I have reinstalled Volta, and it works now.

**Comment by alexdiliberto** [comment]
@charlespierce sure thing

1. Output
```
alexdiliberto@AlexBookPro: ~/.volta/tools/user/bins
$ cat empty-trash.json 
{
  "name": "empty-trash",
  "package": "empty-trash-cli",
  "version": "1.0.1",
  "path": "cli.js",
  "platform": {
    "node": {
      "runtime": "13.2.0",
      "npm": null
    },
    "yarn": null
  }
}
```

2. Cannot find that directory but I do have a `3.14.0/` dir 
```
$ ls ~/.volta/tools/image/packages/empty-trash/1.0.1/
ls: cannot access '/Users/alexdiliberto/.volta/tools/image/packages/empty-trash/1.0.1/': No such file or directory

alexdiliberto@AlexBookPro: ~/.volta/tools/image/packages/ember-cli
$ la 3.14.0/
total 592
-rw-r--r--   1 alexdiliberto staff   1537 Oct 26  1985 .travis.yml
-rw-r--r--   1 alexdiliberto staff 180383 Oct 26  1985 CHANGELOG.md
-rw-r--r--   1 alexdiliberto staff    327 Oct 26  1985 CODE_OF_CONDUCT.md
-rw-r--r--   1 alexdiliberto staff   9230 Oct 26  1985 CONTRIBUTING.md
-rw-r--r--   1 alexdiliberto staff   1128 Oct 26  1985 LICENSE
-rw-r--r--   1 alexdiliberto staff   3124 Oct 26  1985 README.md
-rw-r--r--   1 alexdiliberto staff   7947 Oct 26  1985 RELEASE.md
-rw-r--r--   1 alexdiliberto staff    871 Oct 26  1985 appveyor.yml
drwxr-xr-x   3 alexdiliberto staff     96 Nov 23 21:37 bin/
drwxr-xr-x  15 alexdiliberto staff    480 Nov 23 21:37 blueprints/
drwxr-xr-x  10 alexdiliberto staff    320 Nov 23 21:37 lib/
drwxr-xr-x 565 alexdiliberto staff  18080 Nov 23 21:39 node_modules/
-rw-r--r--   1 alexdiliberto staff 369019 Nov 23 21:39 package-lock.json
-rw-r--r--   1 alexdiliberto staff   5009 Oct 26  1985 package.json
drwxr-xr-x   3 alexdiliberto staff     96 Nov 23 21:37 tests/
```

3. Like you mentioned, same error output
```
$ volta which empty-trash
error: Could not determine path to executable 'empty-trash'

Please rerun the command that triggered this error with the environment
variables `VOLTA_LOGLEVEL` set to `debug` and `RUST_BACKTRACE` set to `full`, and open
an issue at https://github.com/volta-cli/volta/issues with the details!
Error details written to /Users/alexdiliberto/.volta/log/volta-error-2019-12-02_17_53_04.809.log
```

**Comment by alexdiliberto** [comment]
@charlespierce I just went ahead a did a clean install for Volta again and things seem to be working now, I'm not sure how my environment got into that state TBH. I'll leave the issue open if you still want to dig in and try to figure it out, otherwise I can close.

**Comment by charlespierce** [comment]
@alexdiliberto Thanks! Yeah it seems like something failed during the unpack process, but somehow the config files were still written. So it Volta thought everything was set-up, which is why `volta install` was a no-op, but in actuality it didn't work. I'd say leave this open for now, so we can dig into why this failed and see about making sure that we don't leave things in a broken state.

**Comment by kellyselden** [comment]
It looks like I'm having similar issues with pnpm. I'll try reinstalling volta.

**Comment by kellyselden** [comment]
Hmm no dice

```
kselden$ rm -rf ~/.volta
kselden$ curl https://get.volta.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16821    0 16821    0     0  23940      0 --:--:-- --:--:-- --:--:-- 23927
  Installing latest version of Volta (0.6.8)
    Checking for existing Volta installation
    Fetching archive for macOS, version 0.6.8
######################################################################## 100.0%
    Creating directory layout
  Extracting Volta binaries and launchers
x volta
x shim
x load.bash
x load.fish
x load.sh
    Creating symlinks and shims
     Editing user profile (/Users/kselden/.bash_profile)
Warning: Your profile (/Users/kselden/.bash_profile) already mentions Volta and has not been changed.

    Finished installation. Open a new terminal to start using Volta!
kselden$ volta install node
success: installed and set node@12.14.1 (with npm@6.13.4) as default
kselden$ volta install pnpm
success: installed pnpm@4.7.1 with executables: pnpx, pnpm
kselden$ pnpm --version
(node:21857) UnhandledPromiseRejectionWarning: Error: Cannot find module 'pnpm/package.json'
Require stack:
- /Users/kselden/.volta/tools/image/packages/pnpm/4.7.1/lib/node_modules/@pnpm/cli-utils/lib/pnpmPkgJson.js
- /Users/kselden/.volta/tools/image/packages/pnpm/4.7.1/lib/node_modules/@pnpm/cli-utils/lib/getConfig.js
- /Users/kselden/.volta/tools/image/packages/pnpm/4.7.1/lib/node_modules/@pnpm/cli-utils/lib/index.js
- /Users/kselden/.volta/tools/image/packages/pnpm/4.7.1/lib/bin/pnpm.js
- /Users/kselden/.volta/tools/image/packages/pnpm/4.7.1/bin/pnpm.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.resolve (internal/modules/cjs/helpers.js:80:19)
    at Object.<anonymous> (/Users/kselden/.volta/tools/image/packages/pnpm/4.7.1/lib/node_modules/@pnpm/cli-utils/lib/pnpmPkgJson.js:4:43)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/kselden/.volta/tools/image/packages/pnpm/4.7.1/lib/node_modules/@pnpm/cli-utils/lib/getConfig.js:4:23)
(node:21857) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21857) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by charlespierce** [comment]
@kellyselden Apologies for the delay in responding. The error you're seeing looks like it's separate from the parent one. In your case, `pnpm` is _starting_, so the script file is found, but something about how it's installed is different from what is expected, so it's not able to find the right modules when it starts up.

Another complication is that within Volta, we generally treat package managers differently from other packages, since we want to allow you to pin them in your `package.json`, and we haven't yet added support for `pnpm`. It's on our list of tools to support, however, as I know several people have asked about it.

**Comment by lukeed** [comment]
This is consistently reproducible, even with fresh volta installations.

Any "package" that offers a binary cannot be found from within a node process. The only exceptions I've found are:

* node
* npm
* yarn

...but these have been special-cased from what I can tell.

Any other package (`pnpm` for example, which is also a package manager) is hidden from view.

```sh
$ curl https://get.volta.sh | bash
$ volta install node
$ volta install yarn
$ volta install pnpm

$ which npm # /.../.volta/bin/npm
$ which yarn # /.../.volta/bin/yarn
$ which pnpm # /.../.volta/bin/npm

$ node
```

```js
// using "which" dependency
which = require('which')

which.sync('node');
//=> /.../.volta/tools/image/node/12.18.3/bin/node

which.sync('npm');
//=> /.../.volta/tools/image/node/12.18.3/bin/npm

which.sync('yarn');
//=> /.../.volta/tools/image/yarn/1.22.5/bin/yarn

which.sync('pnpm');
//=> Uncaught Error: not found: pnpm

which.sync('sirv');
//=> Uncaught Error: not found: sirv
```

```
# volta list all
⚡️ User toolchain:

    Node runtimes:
        v12.18.3

    Package managers:
        Yarn:
            v1.22.5

    Packages:
        pnpm@5.5.3 (default)
            binary tools: pnpm, pnpx
            platform:
                runtime: node@12.18.3
                package manager: npm@built-in
        sirv-cli@1.0.6 (default)
            binary tools: sirv
            platform:
                runtime: node@12.18.3
                package manager: npm@built-in
```

**Comment by charlespierce** [comment]
@lukeed I think what you're seeing is slightly different from the parent issue, but it _is_ a known issue. See #492 which describes the same behavior you're seeing as well as the proposed solution.

We are working right now on revamping the package install logic, which would include this change as well. See https://github.com/volta-cli/rfcs/pull/45 for more on the work in that area. The goal is to have package installs work seamlessly while still maintaining the benefits that Volta provides.

**Comment by lukeed** [comment]
Ah sorry, I see the difference now :)
Thanks!
