### ISSUE TITLE
git commands run within npm scripts do not work on Windows

### ISSUE THREAD

**Issue by dustinsoftware** [volta-cli/volta#668]
https://github.com/kentcdodds/react-fundamentals/issues/7

![75829412-1b165e00-5d7c-11ea-95c8-b5053df7f7b5](https://user-images.githubusercontent.com/942358/75893673-2d86ab00-5e01-11ea-9a9b-f04db2b7769a.png)

Repro:
Clone `https://github.com/kentcdodds/react-fundamentals/`, and then run `npm run setup` in the cloned folder.

Possibly a relative path issue since `\` and `/` are mixed in the error output?

**Comment by kentcdodds** [comment]
Could you give me the log? That screenshot doesn't say much.

**Comment by dustinsoftware** [comment]
Sure Kent; the log output from node is linked below. Or was there a
different log that I did not attach but would be more helpful?

https://github.com/kentcdodds/react-fundamentals/issues/7#issuecomment-594558997


I am unsure where the relevant Volta logs are or what else would be helpful
for this issue beyond repro steps.

**Comment by kentcdodds** [comment]
Ah, I see, sorry about that. I thought this was on my repo 😅

**Comment by chriskrycho** [comment]
Thanks for reporting! We'll see if we can sort out what's up!

**Comment by charlespierce** [comment]
@dustinsoftware I'm curious if this issue is related to the "mode" selected when `git` was installed? I see in the original issue that you don't see this behavior on a separate machine that has Node 12 installed directly. Is it possible that machine had git installed differently? IIRC, git has a couple of options when you install it on Windows, that control whether it is available in every shell on the machine or _only_ through git bash.

I ask because the error lines appear to be in a `mingw64` directory, which makes me think it is trying to use Git Bash behavior but in PowerShell. That also seems to align with the errors about `basename` and `sed` not existing.

**Comment by dustinsoftware** [comment]
I’ll install Volta on the working machine and see if the error reproduces; that should identify if git installation is being the cause here

**Comment by matiaslato** [comment]
Hi!, I have the same problem, this is the log
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Matias\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'setup'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v12.19.0
4 verbose run-script [ 'presetup', 'setup', 'postsetup' ]
5 info lifecycle @kentcdodds/react-fundamentals@1.0.0~presetup: @kentcdodds/react-fundamentals@1.0.0
6 info lifecycle @kentcdodds/react-fundamentals@1.0.0~setup: @kentcdodds/react-fundamentals@1.0.0
7 verbose lifecycle @kentcdodds/react-fundamentals@1.0.0~setup: unsafe-perm in lifecycle true
8 verbose lifecycle @kentcdodds/react-fundamentals@1.0.0~setup: PATH: C:\Users\Matias\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Matias\Desktop\Proyectos\react-fundamentals\node_modules\.bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Matias\bin;C:\Python39\Scripts;C:\Python39;C:\Python27;C:\Python27\Scripts;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\PuTTY;C:\ProgramData\chocolatey\bin;.;C:\WINDOWS\system32\config\systemprofile\AppData\Local\Android\Sdk\platform-tools";C:\Program Files (x86)\Yarn\bin;C:\Go\bin;C:\ProgramData\ComposerSetup\bin;C:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\Users\Matias\AppData\Local\Microsoft\WindowsApps;C:\Users\Matias\AppData\Local\Programs\Microsoft VS Code\bin;.;C:\Users\Matias\AppData\Local\Android\Sdk\platform-tools";C:\Users\Matias\AppData\Local\Yarn\bin;C:\Users\Matias\go\bin;C:\PHP7;C:\Program Files\Git\mingw64\bin;C:\Users\Matias\AppData\Roaming\Composer\vendor\bin;C:\Users\Matias\AppData\Roaming\npm;C:\Program Files\nodejs
9 verbose lifecycle @kentcdodds/react-fundamentals@1.0.0~setup: CWD: C:\Users\Matias\Desktop\Proyectos\react-fundamentals
10 silly lifecycle @kentcdodds/react-fundamentals@1.0.0~setup: Args: [ '/d /s /c', 'node setup' ]
11 silly lifecycle @kentcdodds/react-fundamentals@1.0.0~setup: Returned: code: 1  signal: null
12 info lifecycle @kentcdodds/react-fundamentals@1.0.0~setup: Failed to exec setup script
13 verbose stack Error: @kentcdodds/react-fundamentals@1.0.0 setup: `node setup`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Matias\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Matias\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid @kentcdodds/react-fundamentals@1.0.0
15 verbose cwd C:\Users\Matias\Desktop\Proyectos\react-fundamentals
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Matias\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "setup"
18 verbose node v12.19.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error @kentcdodds/react-fundamentals@1.0.0 setup: `node setup`
22 error Exit status 1
23 error Failed at the @kentcdodds/react-fundamentals@1.0.0 setup script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by charlespierce** [comment]
Hi @matiaslato, from that error log, it doesn't appear that Volta is involved at all in the process. We don't install Node into `Program Files\nodejs` or npm in `AppData\Roaming\npm`, so I don't believe this is Volta-related. This looks like it's something internal to `@kentcdodds/react-fundamentals` that is failing.

**Comment by charlespierce** [comment]
Closing as this appears to not be an issue. If there are still problems with that package, please feel free to re-open!
