### ISSUE TITLE
volta + npm shrinkwrap issue

### ISSUE THREAD

**Issue by lifeart** [volta-cli/volta#690]
volta 0.7.2

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Users\\lifeart\\AppData\\Local\\Volta\\tools\\image\\node\\12.16.0\\6.13.4\\node.exe',
1 verbose cli   'C:\\Users\\lifeart\\AppData\\Local\\Volta\\tools\\image\\node\\12.16.0\\6.13.4\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.16.0
4 verbose npm-session 90f4678515bf662a
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall planner-frontend@0.0.0
7 info lifecycle planner-frontend@0.0.0~preinstall: planner-frontend@0.0.0
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 timing stage:loadCurrentTree Completed in 1539ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 15ms
14 silly install loadShrinkwrap
15 timing stage:rollbackFailedOptional Completed in 0ms
16 timing stage:runTopLevelLifecycles Completed in 1631ms
17 silly saveTree planner-frontend@0.0.0
17 silly saveTree +-- @ag-grid-community/angular@22.1.2
17 silly saveTree +-- @ag-grid-enterprise/all-modules@22.1.2
17 silly saveTree | +-- @ag-grid-community/all-modules@22.1.1
17 silly saveTree | | +-- @ag-grid-community/client-side-row-model@22.1.1
17 silly saveTree | | | `-- @ag-grid-community/core@22.1.1
17 silly saveTree | | +-- @ag-grid-community/core@22.1.1
17 silly saveTree | | +-- @ag-grid-community/csv-export@22.1.1
17 silly saveTree | | `-- @ag-grid-community/infinite-row-model@22.1.1
17 silly saveTree | +-- @ag-grid-enterprise/charts@22.1.1
17 silly saveTree | | +-- @ag-grid-enterprise/core@22.1.1
17 silly saveTree | | `-- @ag-grid-enterprise/range-selection@22.1.1
17 silly saveTree | +-- @ag-grid-enterprise/clipboard@22.1.1
17 silly saveTree | +-- @ag-grid-enterprise/column-tool-panel@22.1.2
17 silly saveTree | | +-- @ag-grid-enterprise/row-grouping@22.1.1
17 silly saveTree | | `-- @ag-grid-enterprise/side-bar@22.1.1
17 silly saveTree | +-- @ag-grid-enterprise/core@22.1.1
17 silly saveTree | +-- @ag-grid-enterprise/excel-export@22.1.3
17 silly saveTree | +-- @ag-grid-enterprise/filter-tool-panel@22.1.1
17 silly saveTree | +-- @ag-grid-enterprise/master-detail@22.1.1
17 silly saveTree | +-- @ag-grid-enterprise/menu@22.1.1
17 silly saveTree | +-- @ag-grid-enterprise/range-selection@22.1.1
17 silly saveTree | +-- @ag-grid-enterprise/rich-select@22.1.1
17 silly saveTree | +-- @ag-grid-enterprise/row-grouping@22.1.1
17 silly saveTree | +-- @ag-grid-enterprise/server-side-row-model@22.1.2
17 silly saveTree | +-- @ag-grid-enterprise/set-filter@22.1.2
17 silly saveTree | +-- @ag-grid-enterprise/side-bar@22.1.1
17 silly saveTree | +-- @ag-grid-enterprise/status-bar@22.1.2
17 silly saveTree | `-- @ag-grid-enterprise/viewport-row-model@22.1.3
17 silly saveTree +-- @angular-devkit/build-angular@0.13.9
17 silly saveTree | +-- @angular-devkit/architect@0.13.9
17 silly saveTree | | `-- @angular-devkit/core@7.3.9
17 silly saveTree | |   +-- ajv@6.9.1
17 silly saveTree | |   | `-- fast-json-stable-stringify@2.0.0
17 silly saveTree | |   `-- fast-json-stable-stringify@2.0.0
17 silly saveTree | +-- @angular-devkit/build-optimizer@0.13.9
17 silly saveTree | | `-- source-map@0.5.6
17 silly saveTree | +-- @angular-devkit/build-webpack@0.13.9
17 silly saveTree | +-- @angular-devkit/core@7.3.9
17 silly saveTree | +-- ajv@6.9.1
17 silly saveTree | +-- glob@7.1.3
17 silly saveTree | +-- node-sass@4.12.0
17 silly saveTree | | `-- chalk@1.1.3
17 silly saveTree | |   +-- ansi-styles@2.2.1
17 silly saveTree | |   `-- supports-color@2.0.0
17 silly saveTree | +-- parse5@4.0.0
17 silly saveTree | `-- semver@5.6.0
17 silly saveTree +-- @angular/animations@8.2.14
17 silly saveTree +-- @angular/cdk@7.3.7
17 silly saveTree +-- @angular/cli@7.3.9
17 silly saveTree | +-- @angular-devkit/schematics@7.3.9
17 silly saveTree | `-- semver@5.6.0
17 silly saveTree +-- @angular/common@7.2.16
17 silly saveTree +-- @angular/compiler-cli@7.2.16
17 silly saveTree | `-- chokidar@2.1.8
17 silly saveTree |   `-- fsevents@1.2.12
17 silly saveTree |     `-- node-pre-gyp@0.14.0
17 silly saveTree |       +-- detect-libc@1.0.3
17 silly saveTree |       +-- mkdirp@0.5.3
17 silly saveTree |       | `-- minimist@1.2.5
17 silly saveTree |       +-- needle@2.3.3
17 silly saveTree |       | +-- debug@3.2.6
17 silly saveTree |       | | `-- ms@2.1.2
17 silly saveTree |       | +-- iconv-lite@0.4.24
17 silly saveTree |       | | `-- safer-buffer@2.1.2
17 silly saveTree |       | `-- sax@1.2.4
17 silly saveTree |       +-- nopt@4.0.3
17 silly saveTree |       | +-- abbrev@1.1.1
17 silly saveTree |       | `-- osenv@0.1.5
17 silly saveTree |       |   +-- os-homedir@1.0.2
17 silly saveTree |       |   `-- os-tmpdir@1.0.2
17 silly saveTree |       +-- npm-packlist@1.4.8
17 silly saveTree |       | +-- ignore-walk@3.0.3
17 silly saveTree |       | | `-- minimatch@3.0.4
17 silly saveTree |       | |   `-- brace-expansion@1.1.11
17 silly saveTree |       | |     +-- balanced-match@1.0.0
17 silly saveTree |       | |     `-- concat-map@0.0.1
17 silly saveTree |       | +-- npm-bundled@1.1.1
17 silly saveTree |       | | `-- npm-normalize-package-bin@1.0.1
17 silly saveTree |       | `-- npm-normalize-package-bin@1.0.1
17 silly saveTree |       +-- npmlog@4.1.2
17 silly saveTree |       | +-- are-we-there-yet@1.1.5
17 silly saveTree |       | | +-- delegates@1.0.0
17 silly saveTree |       | | `-- readable-stream@2.3.7
17 silly saveTree |       | |   +-- core-util-is@1.0.2
17 silly saveTree |       | |   +-- inherits@2.0.4
17 silly saveTree |       | |   +-- isarray@1.0.0
17 silly saveTree |       | |   +-- process-nextick-args@2.0.1
17 silly saveTree |       | |   +-- safe-buffer@5.1.2
17 silly saveTree |       | |   +-- string_decoder@1.1.1
17 silly saveTree |       | |   `-- util-deprecate@1.0.2
17 silly saveTree |       | +-- console-control-strings@1.1.0
17 silly saveTree |       | +-- gauge@2.7.4
17 silly saveTree |       | | +-- aproba@1.2.0
17 silly saveTree |       | | +-- has-unicode@2.0.1
17 silly saveTree |       | | +-- object-assign@4.1.1
17 silly saveTree |       | | +-- signal-exit@3.0.2
17 silly saveTree |       | | +-- string-width@1.0.2
17 silly saveTree |       | | | +-- code-point-at@1.1.0
17 silly saveTree |       | | | +-- is-fullwidth-code-point@1.0.0
17 silly saveTree |       | | | | `-- number-is-nan@1.0.1
17 silly saveTree |       | | | `-- strip-ansi@3.0.1
17 silly saveTree |       | | |   `-- ansi-regex@2.1.1
17 silly saveTree |       | | +-- strip-ansi@3.0.1
17 silly saveTree |       | | `-- wide-align@1.1.3
17 silly saveTree |       | `-- set-blocking@2.0.0
17 silly saveTree |       +-- rc@1.2.8
17 silly saveTree |       | +-- deep-extend@0.6.0
17 silly saveTree |       | +-- ini@1.3.5
17 silly saveTree |       | `-- strip-json-comments@2.0.1
17 silly saveTree |       +-- rimraf@2.7.1
17 silly saveTree |       | `-- glob@7.1.6
17 silly saveTree |       |   +-- fs.realpath@1.0.0
17 silly saveTree |       |   +-- inflight@1.0.6
17 silly saveTree |       |   | +-- once@1.4.0
17 silly saveTree |       |   | | `-- wrappy@1.0.2
17 silly saveTree |       |   | `-- wrappy@1.0.2
17 silly saveTree |       |   +-- once@1.4.0
17 silly saveTree |       |   `-- path-is-absolute@1.0.1
17 silly saveTree |       +-- semver@5.7.1
17 silly saveTree |       `-- tar@4.4.13
17 silly saveTree |         +-- chownr@1.1.4
17 silly saveTree |         +-- fs-minipass@1.2.7
17 silly saveTree |         | `-- minipass@2.9.0
17 silly saveTree |         |   `-- yallist@3.1.1
17 silly saveTree |         +-- minipass@2.9.0
17 silly saveTree |         +-- minizlib@1.3.3
17 silly saveTree |         `-- yallist@3.1.1
17 silly saveTree `-- @angular/compiler@7.2.16
18 verbose stack TypeError: Cannot read property 'match' of undefined
18 verbose stack     at tarballToVersion (C:\Users\lifeart\AppData\Local\Volta\tools\image\node\12.16.0\6.13.4\node_modules\npm\lib\install\inflate-shrinkwrap.js:87:20)
18 verbose stack     at inflatableChild (C:\Users\lifeart\AppData\Local\Volta\tools\image\node\12.16.0\6.13.4\node_modules\npm\lib\install\inflate-shrinkwrap.js:99:22)
18 verbose stack     at C:\Users\lifeart\AppData\Local\Volta\tools\image\node\12.16.0\6.13.4\node_modules\npm\lib\install\inflate-shrinkwrap.js:55:12
18 verbose stack     at tryCatcher (C:\Users\lifeart\AppData\Local\Volta\tools\image\node\12.16.0\6.13.4\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
18 verbose stack     at Object.gotValue (C:\Users\lifeart\AppData\Local\Volta\tools\image\node\12.16.0\6.13.4\node_modules\npm\node_modules\bluebird\js\release\reduce.js:155:18)
18 verbose stack     at Object.gotAccum (C:\Users\lifeart\AppData\Local\Volta\tools\image\node\12.16.0\6.13.4\node_modules\npm\node_modules\bluebird\js\release\reduce.js:144:25)
18 verbose stack     at Object.tryCatcher (C:\Users\lifeart\AppData\Local\Volta\tools\image\node\12.16.0\6.13.4\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
18 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\lifeart\AppData\Local\Volta\tools\image\node\12.16.0\6.13.4\node_modules\npm\node_modules\bluebird\js\release\promise.js:517:31)
18 verbose stack     at Promise._settlePromise (C:\Users\lifeart\AppData\Local\Volta\tools\image\node\12.16.0\6.13.4\node_modules\npm\node_modules\bluebird\js\release\promise.js:574:18)
18 verbose stack     at Promise._settlePromise0 (C:\Users\lifeart\AppData\Local\Volta\tools\image\node\12.16.0\6.13.4\node_modules\npm\node_modules\bluebird\js\release\promise.js:619:10)
18 verbose stack     at Promise._settlePromises (C:\Users\lifeart\AppData\Local\Volta\tools\image\node\12.16.0\6.13.4\node_modules\npm\node_modules\bluebird\js\release\promise.js:699:18)
18 verbose stack     at _drainQueueStep (C:\Users\lifeart\AppData\Local\Volta\tools\image\node\12.16.0\6.13.4\node_modules\npm\node_modules\bluebird\js\release\async.js:138:12)
18 verbose stack     at _drainQueue (C:\Users\lifeart\AppData\Local\Volta\tools\image\node\12.16.0\6.13.4\node_modules\npm\node_modules\bluebird\js\release\async.js:131:9)
18 verbose stack     at Async._drainQueues (C:\Users\lifeart\AppData\Local\Volta\tools\image\node\12.16.0\6.13.4\node_modules\npm\node_modules\bluebird\js\release\async.js:147:5)
18 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\lifeart\AppData\Local\Volta\tools\image\node\12.16.0\6.13.4\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
18 verbose stack     at processImmediate (internal/timers.js:456:21)
19 verbose cwd C:\Users\lifeart\Documents\repos\unifiedplanner\planner-frontend
20 verbose Windows_NT 10.0.18363
21 verbose argv "C:\\Users\\lifeart\\AppData\\Local\\Volta\\tools\\image\\node\\12.16.0\\6.13.4\\node.exe" "C:\\Users\\lifeart\\AppData\\Local\\Volta\\tools\\image\\node\\12.16.0\\6.13.4\\node_modules\\npm\\bin\\npm-cli.js" "install"
22 verbose node v12.16.0
23 verbose npm  v6.13.4
24 error Cannot read property 'match' of undefined
25 verbose exit [ 1, true ]


```
[inflate-shrinkwrap.zip](https://github.com/volta-cli/volta/files/4389532/inflate-shrinkwrap.zip)

**Comment by rwjblue** [comment]
@lifeart - What command was ran? How can we reproduce?

**Comment by charlespierce** [comment]
@lifeart This doesn't appear, on the surface, to be an issue with Volta. Volta is responsible for launching the tools (in this case `npm` with `node`), after that it cedes control to the tool and isn't involved any more. In this case, `npm` is running and then running into an error, so it most likely is an issue with `npm`. It's possible that there's something with the filesystem layout that Volta uses that could be causing issues, but given that the error doesn't appear to be related to reading internal `npm` files, that doesn't seem to be the case.

Some quick searching seems to indicate this error is pretty common when the `npm-shrinkwrap.json` / `package-lock.json` gets written without a version or in an invalid way: https://npm.community/t/npm-err-cannot-read-property-match-of-undefined/234

**Comment by lifeart** [comment]
@rwjblue `npm install` with `npm-shrinkwrap.json` file inside dir.

**Comment by lifeart** [comment]
@charlespierce thank you for fast response! I will check possible issues with `npm-shrinkwrap.json` itself.
