### ISSUE TITLE
Unable to install typescript

### ISSUE THREAD

**Issue by takase1121** [volta-cli/volta#759]
Volta is a savior when trying to install node on Windows.
But I tried to install `typescript` and got error:
```
error: Could not download package metadata for 'typescript'

Please ensure the requested package name is correct.
```

How do I resolve this?

EDIT:
Running with `--verbose` exposes more info, but I still have no idea what is going on.
```
volta install --verbose typescript
[verbose] No custom hooks found
[verbose] Found project manifest in 'C:\Users\Takase\Desktop\helpme\pino-discord-webhook'
[verbose] Found default configuration at 'C:\Users\Takase\AppData\Local\Volta\tools\user\platform.json'
[verbose] node@12.18.0 has already been fetched, skipping download
[verbose] npm@6.14.5 has already been fetched, skipping download
[verbose] Using npm@6.14.5 from default configuration
[verbose] Running command: `"cmd.exe" "/C" "npm" "view" "--json" "typescript@latest"`
[verbose] Command failed, stderr is:
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'C:\Users\Takase\AppData\Local\Volta\tools\image\npm\6.14.5\bin\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'C:\Users\Takase\AppData\Local\Volta\tools\image\npm\6.14.5\bin\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

[verbose] Exit code is Some(1)
error: Could not download package metadata for 'typescript'

Please ensure the requested package name is correct.
```
EDIT2:
Volta 0.8.1 on Windows 10

**Comment by takase1121** [comment]
I deleted `appdata/Local/Volta`, and proceeded to reinstall node. Now it worked. I still have no idea what happened.

**Comment by charlespierce** [comment]
Hmm, that's super strange! Seems like something got corrupted, but not sure what would cause it to be completely broken like that. Glad that clearing out the Volta dir worked, but sorry it was necessary!
